import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { LEGAL_EMAIL, LEGAL_LOCATION, LEGAL_OPERATOR } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms of Service — Vicero",
  description:
    "The terms for using Vicero: accounts, acceptable use, messaging consent, billing, AI output, liability and governing law.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro={`These terms are an agreement between you and ${LEGAL_OPERATOR}, ${LEGAL_LOCATION} ("we", "us") for your use of Vicero. By creating an account or using the service you accept them.`}
    >
      <LegalSection title="1. The service">
        <p>
          Vicero lets you create AI chatbots, give them a knowledge base, embed a chat widget, connect messaging channels
          (such as WhatsApp Business, Facebook Messenger and Instagram) and wire up automations. Features and limits depend on
          your plan and may change over time.
        </p>
      </LegalSection>

      <LegalSection title="2. Accounts">
        <p>
          You must give accurate information, keep your credentials safe and be authorised to bind the business you sign up
          for. You are responsible for activity under your account and for the people you invite to your organization. Tell us
          promptly if you suspect unauthorised access.
        </p>
      </LegalSection>

      <LegalSection title="3. Acceptable use">
        <p>You agree not to use Vicero to:</p>
        <ul>
          <li>send spam, unsolicited bulk messages or messages to people who have not agreed to receive them;</li>
          <li>create, store or send illegal, fraudulent, harassing, hateful or deceptive content, or malware;</li>
          <li>infringe anyone&apos;s rights or collect personal data unlawfully;</li>
          <li>
            break the terms or policies of the platforms you connect, including the Meta Platform Terms, the WhatsApp
            Business Terms and WhatsApp Business and Commerce Policies;
          </li>
          <li>probe, overload or bypass the security or limits of the service, or resell it except as we have agreed.</li>
        </ul>
        <p>We may suspend content or accounts that breach these rules.</p>
      </LegalSection>

      <LegalSection title="4. Messaging consent and WhatsApp rules">
        <p>
          You are solely responsible for having a lawful basis and any required opt-in consent before your chatbot messages
          anyone, and for honouring opt-outs. On WhatsApp you must follow the 24-hour customer service window: free-form
          replies are allowed only within 24 hours of the user&apos;s last message, and outside that window only approved
          message templates may be sent. Messaging-provider charges are billed to you by that provider.
        </p>
      </LegalSection>

      <LegalSection title="5. Plans, billing and cancellation">
        <p>
          Paid plans are billed monthly, in advance, at the price shown for your plan, and each limit applies per workspace.
          Taxes may be added where they apply. You can cancel at any time and the plan runs until the end of the period you
          have paid for. Except where the law requires otherwise, fees already paid are not refunded.
        </p>
      </LegalSection>

      <LegalSection title="6. AI output">
        <p>
          Chatbot replies are generated by AI models and can be inaccurate, incomplete or out of date. You are responsible for
          reviewing how your chatbot behaves and for what it tells your customers, and it must not be relied on for medical,
          legal, financial or other professional advice. Use human review for anything high-stakes.
        </p>
      </LegalSection>

      <LegalSection title="7. Third-party platforms">
        <p>
          Channels such as WhatsApp, Messenger and Instagram are provided by Meta, and AI models by third-party providers.
          Their own terms and policies apply to your use of them, and they may change or withdraw access without us being
          able to prevent it. We are not responsible for their services.
        </p>
      </LegalSection>

      <LegalSection title="8. Your data and our intellectual property">
        <p>
          You keep ownership of your content, including your knowledge base and your end users&apos; conversations, and give
          us the right to host and process it to provide the service. How we handle personal data is described in our{" "}
          <Link href="/privacy">Privacy Policy</Link>. Vicero, its software and its branding belong to us; these terms give
          you a limited, non-exclusive right to use the service and nothing more.
        </p>
      </LegalSection>

      <LegalSection title="9. Termination">
        <p>
          You may stop using Vicero and delete your organization at any time. We may suspend or end your access if you breach
          these terms, put the service or other users at risk, or fail to pay. On termination your data is deleted as
          described in the Privacy Policy and on the <Link href="/data-deletion">data deletion page</Link>.
        </p>
      </LegalSection>

      <LegalSection title="10. Disclaimers and limitation of liability">
        <p>
          Vicero is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind to the extent the
          law allows. To the maximum extent permitted by law, we are not liable for indirect, incidental or consequential
          loss, lost profits or lost data, and our total liability for any claim is limited to the fees you paid us in the
          three months before the event giving rise to it. Nothing here limits liability that cannot be limited by law.
        </p>
      </LegalSection>

      <LegalSection title="11. Governing law">
        <p>
          These terms are governed by the laws of India. The courts at Chennai, Tamil Nadu have exclusive jurisdiction over
          disputes, subject to any mandatory rights you have under the law where you live.
        </p>
      </LegalSection>

      <LegalSection title="12. Changes and contact">
        <p>
          We may update these terms; the &quot;Last updated&quot; date shows the current version, and continued use after a
          change means you accept it. Questions: {LEGAL_OPERATOR}, {LEGAL_LOCATION},{" "}
          <a href={`mailto:${LEGAL_EMAIL}`}>{LEGAL_EMAIL}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
